### ISSUE TITLE
Tradução: BasicOperators.md - Logical NOT Operator

### ISSUE THREAD

**Issue by GabrielaBezerra** [AcademyIFCE/swift-book#34]
Traduza o conteúdo de [BasicOperators.md - Logical NOT Operator](../blob/main/Sources/TSPL/TSPL.docc/LanguageGuide/BasicOperators.md#logical-not-operator)

**Comment by elisionara** [comment]
Traduzindo

**Comment by elisionara** [comment]
Traduzido ✅
