### ISSUE TITLE
Tradução: AdvancedOperators.md - Bitwise Left and Right Shift Operators

### ISSUE THREAD

**Issue by GabrielaBezerra** [AcademyIFCE/swift-book#48]
Traduza o conteúdo de [AdvancedOperators.md - Bitwise Left and Right Shift Operators](../blob/main/Sources/TSPL/TSPL.docc/LanguageGuide/AdvancedOperators.md#bitwise-left-and-right-shift-operators)

**Comment by elisionara** [comment]
Traduzindo...
