### ISSUE TITLE
Tradução: AdvancedOperators.md - Shifting Behavior for Unsigned Integers

### ISSUE THREAD

**Issue by GabrielaBezerra** [AcademyIFCE/swift-book#49]
Traduza o conteúdo de [AdvancedOperators.md - Shifting Behavior for Unsigned Integers](../blob/main/Sources/TSPL/TSPL.docc/LanguageGuide/AdvancedOperators.md#shifting-behavior-for-unsigned-integers)

**Comment by lucasbaptist** [comment]
Traduzindo
